### ISSUE TITLE
Error while loading data

### ISSUE THREAD

**Issue by FR-TheS** [lmenezes/cerebro#126]
Hi,

I have done a new local installation of elasticsearch v5.3 + cerebro v0.6.5.
When i put my host http://localhost:9200/, cerebro echo "Error while loading data".
Same with http://127.0.0.1:9200/.

Elastic work if I try get on http://localhost:9200/

> {
>   "name" : "YcPy6i4",
>   "cluster_name" : "elasticsearch",
>   "cluster_uuid" : "_9teDAg2The-HhfV6CQnHw",
>   "version" : {
>     "number" : "5.3.0",
>     "build_hash" : "3adb13b",
>     "build_date" : "2017-03-23T03:31:50.652Z",
>     "build_snapshot" : false,
>     "lucene_version" : "6.4.1"
>   },
>   "tagline" : "You Know, for Search"
> }

Did I missed something?

Thank for your help.

**Comment by lmenezes** [comment]
You don't need the / after the port. Could you try that?

**Comment by FR-TheS** [comment]
Oh great, it seems to working :).
Perfect !
Thank you, maybe you can auto remove the last slash if found

Cordialement,

[image: Administrateur Systèmes Windows]


ALEXANDRE Steve
alexandre.steve95@gmail.com / +33 6 68 18 86 52

Administrateur Systèmes Windows
Saint-Ouen-L'Aumône (95310)

[image: LinkedIn] <https://htmlsig.com/t/0000001BT772G> [image: Stack
Overflow] <https://htmlsig.com/t/0000001BVS4E8>

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

2017-04-11 14:47 GMT+02:00 leonardo menezes <notifications@github.com>:

**Comment by joan38** [comment]
Hi guys,

I'm getting the same issue with 0.7.1 and ES 5.5.1 without trailing slash.
Do you know how can I debug this?

Here is by `docker-compose.yml`:
```
version: '2'
services:

  # Cerebro Elasticsearch client
  cerebro:
    image: dylanmei/cerebro:latest
    ports:
      - "9000:9000"
    networks:
      - app_net

  # Elasticsearch cluster
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    environment:
      - cluster.name=es-cluster
      - node.name=es1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app_net

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    environment:
      - cluster.name=es-cluster
      - node.name=es2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - "9201:9200"
      - "9301:9300"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
```

Regards
