### ISSUE TITLE
Add max-width to alerts as they are too wide on wide monitors

### ISSUE THREAD

**Issue by MonnyA** [lmenezes/cerebro#171]
Suggested change in /src/app/css/app.css line 64.
Add a max-width attribute to .alerts class, as on a wide monitor (2560 x 1080) the alerts are way too wide. I picked 700px as I think it looks good, but it's up for debate, hence no pull request.

Before:
```css
.alerts { padding-top: 40px; position: fixed; padding-left: 50px; right: 25px; width: 50%; top: 30px; z-index: 1000000; }
```
![c1](https://user-images.githubusercontent.com/8193077/27743783-08ed2b10-5db5-11e7-913d-905e1b46ed2e.png)

After:
```css
.alerts { padding-top: 40px; position: fixed; padding-left: 50px; right: 25px; width: 50%; max-width: 700px; top: 30px; z-index: 1000000; }
```
![c2](https://user-images.githubusercontent.com/8193077/27743794-111d20a6-5db5-11e7-9e7c-061d7401ba8e.png)
