### ISSUE TITLE
Error while loading request history

### ISSUE THREAD

**Issue by daplho** [lmenezes/cerebro#283]
Running `cerebro` using stock settings but authenticated to a cert elasticsearch cluster, I always get an error while trying to load `previous requests` in the `rest` tab. More specifically, this calls out to the `http://localhost:9000/rest/history` endpoint and  returns the following error there:

```
{"status":500,"body":{"Error":"Error while loading requests history: Error loading requests for [admin]"}}
```

No errors show up in the logs. Can someone give me some advice on moving forward on this?

**Comment by daplho** [comment]
^^

**Comment by mt3593** [comment]
I get a similar issue mine returns:

**Comment by daplho** [comment]
@lmenezes any update on this?

**Comment by mt3593** [comment]
@daplho I've managed to get mine working but this could be down to the setup I had. 

My setup was running `cerebro` via [yannart cerebro](https://github.com/yannart/docker-cerebro) docker image on a k8's cluster. To update the config I mounted a drive that had all the files expected in the `/opt/cerbro/conf`.

What I didn't realise is that the config only stores to one level, this means that the `evolutions` folder was not being put into the config (this is a k8's thing). 

What I also noticed was no `cerbro.db` was being created at the startup. 

I've fixed this by only overriding the `application.conf` location at startup, so now my history works :+1: 

I've also downloaded and ran this project with `sbt run` and can see everything working as expected.

All in all this was down to my specific setup, so my bad. 


How do you have your's setup @daplho ? does any of the above help?

**Comment by daplho** [comment]
Yes @mt3593 - the above helps. In particular, I had missed the significance of the `evolutions` folder and fallen for the trap of it not being created out of the k8s configmap.

I've addressed this by overriding the `application.conf` only using `subPath` for `volumeMounts`. Here is the relevant section out of my k8s yaml for reference:

```
        volumeMounts:
          - mountPath: /usr/cerebro/conf/application.conf
            name: cerebro-config
            subPath: application.conf
      volumes:
        - name: cerebro-config
          configMap:
            name: cerebro-config
```
