### ISSUE TITLE
Invalid HTTP port 

### ISSUE THREAD

**Issue by laoshancun** [lmenezes/cerebro#441]
`Invalid HTTP port: tcp://172.31.14.133:9000` when upgrade from 0.8.5 to 0.9.0.

**Comment by moliware** [comment]
Could you elaborate a bit more on this?

Not sure if related but we introduced these changes regarding the port:
- #438 
- https://github.com/lmenezes/cerebro-docker/pull/5

**Comment by laoshancun** [comment]
Server:Docker
Env:none
Image:lmenezes/cerebro:0.9.0

**Comment by laoshancun** [comment]
## Container Stdout
![20200512153015](https://user-images.githubusercontent.com/4952748/81651848-8c9e1700-9465-11ea-89c2-061a7acc9d0e.png)
## Pod yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: cerebro
    pod-template-hash: "6954484579"
  name: cerebro-6954484579-kdnhj
spec:
  containers:
  - image: lmenezes/cerebro:0.9.0
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 9000
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 2
    name: cerebro
    ports:
    - containerPort: 9000
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 9000
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 2
      timeoutSeconds: 2
    resources:
      limits:
        cpu: 500m
        memory: 800Mi
      requests:
        cpu: 100m
        memory: 800Mi
    securityContext:
      capabilities: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-b4655
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
```

**Comment by BitProcessor** [comment]
Can also confirm that 0.8.5 works, while 0.9.1 is giving the Invalid HTTP Port error. 
Also running on Kubernetes.

**Comment by vmercierfr** [comment]
We experienced similar issue during upgrade to Cerebro 9.0
We identified the root cause with a workaround.

**Root cause:**

Cerebro 9.0 introduced `CEREBRO_PORT` environment variable to set the daemon port (See https://github.com/lmenezes/cerebro/commit/04b5ca8935cdf49e11aa125aeab6121e5bdd466a).
This variable could conflicts with Kubernetes deployment.

Kubernetes generates (by default) environment variables for services deployed in same namespace (see https://kubernetes.io/docs/concepts/services-networking/service/#environment-variables).
If you deploy Cerebro with a Kubernetes service called `cerebro`, the `CEREBRO_PORT` environment variable will be automatically defined to `tcp://<pod_id_address>:9000`.

When Cerebro starts, it execute `server.http.port = tcp://<pod_id_address>:9000` and crash with the following error:
```
Invalid HTTP port: tcp://<pod_id_address>:9000
```

**Work-around**

We identified 2 workarounds:

1. Override `CEREBRO_PORT` to force Cerebro port. You may add the following lines to your container:
    ```yaml
    env:
    - name: "CEREBRO_PORT"
      value: "9000"
    ```
2. Set `enableServiceLinks=false` in your pod deployment (See https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service) to avoid environment variables conflicts
